// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_ARyOApATFvwbtAOBNvZLD3PbhsYXHQ',
    appId: '1:657898044552:web:4e2dd2de684940bc4a333d',
    messagingSenderId: '657898044552',
    projectId: 'hopin-51e85',
    authDomain: 'hopin-51e85.firebaseapp.com',
    storageBucket: 'hopin-51e85.firebasestorage.app',
    measurementId: 'G-Q8M3EEQQ27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_ARyOApATFvwbtAOBNvZLD3PbhsYXHQ',
    appId: '1:657898044552:android:a168b16a84bbaed84a333d',
    messagingSenderId: '657898044552',
    projectId: 'hopin-51e85',
    storageBucket: 'hopin-51e85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7nxOzrMYmkqRGKZBXyYetkMeODwa38b0',
    appId: '1:657898044552:ios:118ee16b100545ef4a333d',
    messagingSenderId: '657898044552',
    projectId: 'hopin-51e85',
    storageBucket: 'hopin-51e85.firebasestorage.app',
    iosBundleId: 'com.hopin.student.hopinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7nxOzrMYmkqRGKZBXyYetkMeODwa38b0',
    appId: '1:657898044552:ios:118ee16b100545ef4a333d',
    messagingSenderId: '657898044552',
    projectId: 'hopin-51e85',
    storageBucket: 'hopin-51e85.firebasestorage.app',
    iosBundleId: 'com.hopin.student.hopinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD_ARyOApATFvwbtAOBNvZLD3PbhsYXHQ',
    appId: '1:657898044552:web:4e2dd2de684940bc4a333d',
    messagingSenderId: '657898044552',
    projectId: 'hopin-51e85',
    authDomain: 'hopin-51e85.firebaseapp.com',
    storageBucket: 'hopin-51e85.firebasestorage.app',
    measurementId: 'G-Q8M3EEQQ27',
  );
} 